spring:
  cloud:
    gateway:
      routes:
        - id: band-booking
          uri: lb://BAND-BOOKING
          predicates:
            - Path= /band/**
          filters:
            - name: CircuitBreaker
              args:
                name: band-booking
                fallbackuri: bandBookingService

        - id: user-login
          uri: lb://USER-LOGIN
          predicates:
               Path= /auth/**

        - id: registration-booking
          uri: lb://REGISTRATION-BOOKING
          predicates:
            - Path= /**
          filters:
            - name: CircuitBreaker
              args:
                name: registration-booking
                fallbackuri: forward:/registrationService

#        - id: user-login
#          uri: lb://USER-LOGIN
#          predicates:
#            - Path= /auth/**
#          filters:
#            - name: CircuitBreaker
#              args:
#                name: user-login
#                fallbackuri: forward:/userlogin
  security:
    user:
      name: harsh
      password: harsh


#management:
#  endpoints:
#    web:
#      exposure:
#        include: hystrix.stream
#
#hystrix:
#  command:
#    fallbackcmd:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 5000



eureka:
  application:
    name: API-GATEWAY
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
#  instance:
