spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
#        - id: user-login
#          uri: lb://user-login
#          predicates:
#            - Path=/login/**
        - id: band-booking
          uri: lb://band-booking
          predicates:
            - Path = /**



server:
  port: 8989

eureka:
  application:
    name: API-GATEWAY
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
#  instance:
