spring:
  application:
  name: band-booking
server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
#  instance:
#    prefer-ip-address: false  # <== Important: don't prefer IP
#    hostname: localhost  # <== Your custom name
#    instance-id: BAND-BOOKING
