spring:
  application:
  name: registration-booking
server:
  port: 8081

eureka:
  application:
    name: REGISTRATION-BOOKING
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
